### PR TITLE
Implements `apps.connections.open` Spec

### LINKED ISSUE #54: New Socket mode not described here
### Description

The docs for new slack apps say to use the new `Socket Mode` and that the `RTM` client mode is deprecated:
https://api.slack.com/rtm

New mode is described here: https://api.slack.com/apis/connections/socket

Yet there don't seem to be any schemas for `apps.connections.open` as the first step in connecting with the new mode: https://api.slack.com/methods/apps.connections.open

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-api-specs/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

No schema seems to be defined for https://api.slack.com/methods/apps.connections.open

#### Steps to reproduce:

1. self-explanatory

#### Expected result:

Documented schema available - if new apps are automatically pushed over to Socket Mode instead.

### PR DESCRIPTION
**Pull request by platinummonkey**
###  Submitting a PR

```
Our open Web API specification is an artifact. It's the end result of an incredible machine (well, a Python script) compiling all the facts, fibs, schemas, and articulated examples across hundreds of individual files that describe our platform internally.

As such, we cannot accept pull requests on these spec files. Please file an Issue if you have questions, suggestions or feedback.
``` 
^ seems like this is broken too 😉 

- Add missing [apps.connections.open](https://api.slack.com/methods/apps.connections.open) spec
- add missing security auth method for Authorization Bearer

fixes #54

### CODE REVIEW

**Comment by platinummonkey** [comment]
🦗 it's been 3 months 🦗

**Comment by platinummonkey** [comment]
🦗 it's been 5 months 🦗

**Comment by filmaj** [comment]
Hey @platinummonkey, sorry for the lack of response here.

> ^ seems like this is broken too 😉

Actually that line in the README is intentional. We don't accept contributions from the community in this project right now, though we hope to revisit that in the future. It's not a great answer, and we should have responded to you sooner. I apologize for that.

**Comment by platinummonkey** [comment]
https://github.com/slackapi/slack-api-specs/issues/54 is still open then :) Is that spec expected to be published?

**Comment by filmaj** [comment]
Indeed it is still open, and we appreciate you filing the issue. At this point we are still figuring out how to appropriately serve the community through this repo, which is why we are not accepting community contributions to it at this time. Once we have this effort staffed appropriately, we will better be able to work with y'all on making this a healthy, active and useful project. Unfortunately, that's not where we are at with it at the moment. I'm sorry I don't have a better answer for your right now 😞

**Pull request closed without merging**
